version: '3.9'

services:
  security:
    depends_on:
      - MySqlDB
      - PhpMyAdmin
    build: ./security
    image: security
    container_name: security
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app


  MySqlDB:
    image: mysql:8.0
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/data-mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: app-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 55555
      MYSQL_ROOT_PASSWORD: 55555
    networks:
      - app

  PhpMyAdmin:
    depends_on:
      - MySqlDB
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_PORT: db
      MYSQL_ROOT_PASSWORD: 55555
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  db: