version: '3.9'

services:
  Nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - SecurityApplication
      - NoSqlApplication
    networks:
      - app

  SecurityApplication:
    depends_on:
      - PhpMyAdmin
      - NoSqlApplication
    build: ./security
    image: security
    container_name: security
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app


  NoSqlApplication:
    depends_on:
      - MongoExpress
    build: ./NoSqlDB
    image: nosql-app
    container_name: nosql-app
    restart: always
    ports:
      - '5001:5001'
    networks:
      - app


  MySqlDB:
    image: mysql:8.0
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/data-mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: security
      MYSQL_USER: admin
      MYSQL_PASSWORD: 55555
      MYSQL_ROOT_PASSWORD: 55555
    networks:
      - app


  PhpMyAdmin:
    depends_on:
      - MySqlDB
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_PORT: db
      MYSQL_ROOT_PASSWORD: 55555
    networks:
      - app


  MongoDB:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - 27017
    extra_hosts:
      - 127.0.0.1:127.0.0.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=55555
      - MONGO_INITDB_DATABASE=NoSqlDB
    volumes:
      - ./database/data-mongodb:/data/db
    networks:
      - app


  MongoExpress:
    depends_on:
      - MongoDB
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 55555
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app


networks:
  app:
    driver: bridge
volumes:
  MySqlDB:
  Mongodb: